/*
 *    MCreator note:
 *
 *    This file is autogenerated to connect all MCreator mod elements together.
 *
 */
package net.mcreator.gyisti;

import net.minecraftforge.forgespi.language.ModFileScanData;
import net.minecraftforge.fml.network.NetworkEvent;
import net.minecraftforge.fml.event.server.FMLServerStartingEvent;
import net.minecraftforge.fml.event.lifecycle.FMLCommonSetupEvent;
import net.minecraftforge.fml.event.lifecycle.FMLClientSetupEvent;
import net.minecraftforge.fml.ModList;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.api.distmarker.OnlyIn;
import net.minecraftforge.api.distmarker.Dist;

import net.minecraft.world.biome.Biome;
import net.minecraft.util.ResourceLocation;
import net.minecraft.tags.Tag;
import net.minecraft.network.PacketBuffer;
import net.minecraft.item.Item;
import net.minecraft.entity.EntityType;
import net.minecraft.enchantment.Enchantment;
import net.minecraft.block.Block;

import java.util.function.Supplier;
import java.util.function.Function;
import java.util.function.BiConsumer;
import java.util.Set;
import java.util.Map;
import java.util.List;
import java.util.HashMap;
import java.util.Collections;
import java.util.ArrayList;

import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Retention;

public class GyistiModElements {
	public final List<ModElement> elements = new ArrayList<>();
	public final List<Supplier<Block>> blocks = new ArrayList<>();
	public final List<Supplier<Item>> items = new ArrayList<>();
	public final List<Supplier<Biome>> biomes = new ArrayList<>();
	public final List<Supplier<EntityType<?>>> entities = new ArrayList<>();
	public final List<Supplier<Enchantment>> enchantments = new ArrayList<>();
	public static Map<ResourceLocation, net.minecraft.util.SoundEvent> sounds = new HashMap<>();
	public GyistiModElements() {
		sounds.put(new ResourceLocation("gyisti", "youareanidiot"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("gyisti", "youareanidiot")));
		sounds.put(new ResourceLocation("gyisti", "ai_scp"), new net.minecraft.util.SoundEvent(new ResourceLocation("gyisti", "ai_scp")));
		sounds.put(new ResourceLocation("gyisti", "amongus"), new net.minecraft.util.SoundEvent(new ResourceLocation("gyisti", "amongus")));
		sounds.put(new ResourceLocation("gyisti", "blue"), new net.minecraft.util.SoundEvent(new ResourceLocation("gyisti", "blue")));
		sounds.put(new ResourceLocation("gyisti", "bump"), new net.minecraft.util.SoundEvent(new ResourceLocation("gyisti", "bump")));
		sounds.put(new ResourceLocation("gyisti", "fnaf"), new net.minecraft.util.SoundEvent(new ResourceLocation("gyisti", "fnaf")));
		sounds.put(new ResourceLocation("gyisti", "mandre"), new net.minecraft.util.SoundEvent(new ResourceLocation("gyisti", "mandre")));
		sounds.put(new ResourceLocation("gyisti", "scpradio"), new net.minecraft.util.SoundEvent(new ResourceLocation("gyisti", "scpradio")));
		sounds.put(new ResourceLocation("gyisti", "shaun"), new net.minecraft.util.SoundEvent(new ResourceLocation("gyisti", "shaun")));
		sounds.put(new ResourceLocation("gyisti", "showyourself"), new net.minecraft.util.SoundEvent(new ResourceLocation("gyisti", "showyourself")));
		sounds.put(new ResourceLocation("gyisti", "yourlastwarning"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("gyisti", "yourlastwarning")));
		sounds.put(new ResourceLocation("gyisti", "yourrast"), new net.minecraft.util.SoundEvent(new ResourceLocation("gyisti", "yourrast")));
		sounds.put(new ResourceLocation("gyisti", "timmy"), new net.minecraft.util.SoundEvent(new ResourceLocation("gyisti", "timmy")));
		sounds.put(new ResourceLocation("gyisti", "ugotthat"), new net.minecraft.util.SoundEvent(new ResourceLocation("gyisti", "ugotthat")));
		sounds.put(new ResourceLocation("gyisti", "boom"), new net.minecraft.util.SoundEvent(new ResourceLocation("gyisti", "boom")));
		sounds.put(new ResourceLocation("gyisti", "melo"), new net.minecraft.util.SoundEvent(new ResourceLocation("gyisti", "melo")));
		sounds.put(new ResourceLocation("gyisti", "mely"), new net.minecraft.util.SoundEvent(new ResourceLocation("gyisti", "mely")));
		sounds.put(new ResourceLocation("gyisti", "mors"), new net.minecraft.util.SoundEvent(new ResourceLocation("gyisti", "mors")));
		try {
			ModFileScanData modFileInfo = ModList.get().getModFileById("gyisti").getFile().getScanResult();
			Set<ModFileScanData.AnnotationData> annotations = modFileInfo.getAnnotations();
			for (ModFileScanData.AnnotationData annotationData : annotations) {
				if (annotationData.getAnnotationType().getClassName().equals(ModElement.Tag.class.getName())) {
					Class<?> clazz = Class.forName(annotationData.getClassType().getClassName());
					if (clazz.getSuperclass() == GyistiModElements.ModElement.class)
						elements.add((GyistiModElements.ModElement) clazz.getConstructor(this.getClass()).newInstance(this));
				}
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
		Collections.sort(elements);
		elements.forEach(GyistiModElements.ModElement::initElements);
		MinecraftForge.EVENT_BUS.register(new GyistiModVariables(this));
	}

	public void registerSounds(RegistryEvent.Register<net.minecraft.util.SoundEvent> event) {
		for (Map.Entry<ResourceLocation, net.minecraft.util.SoundEvent> sound : sounds.entrySet())
			event.getRegistry().register(sound.getValue().setRegistryName(sound.getKey()));
	}
	private int messageID = 0;
	public <T> void addNetworkMessage(Class<T> messageType, BiConsumer<T, PacketBuffer> encoder, Function<PacketBuffer, T> decoder,
			BiConsumer<T, Supplier<NetworkEvent.Context>> messageConsumer) {
		GyistiMod.PACKET_HANDLER.registerMessage(messageID, messageType, encoder, decoder, messageConsumer);
		messageID++;
	}

	public List<ModElement> getElements() {
		return elements;
	}

	public List<Supplier<Block>> getBlocks() {
		return blocks;
	}

	public List<Supplier<Item>> getItems() {
		return items;
	}

	public List<Supplier<Biome>> getBiomes() {
		return biomes;
	}

	public List<Supplier<EntityType<?>>> getEntities() {
		return entities;
	}

	public List<Supplier<Enchantment>> getEnchantments() {
		return enchantments;
	}
	public static class ModElement implements Comparable<ModElement> {
		@Retention(RetentionPolicy.RUNTIME)
		public @interface Tag {
		}
		protected final GyistiModElements elements;
		protected final int sortid;
		public ModElement(GyistiModElements elements, int sortid) {
			this.elements = elements;
			this.sortid = sortid;
		}

		public void initElements() {
		}

		public void init(FMLCommonSetupEvent event) {
		}

		public void serverLoad(FMLServerStartingEvent event) {
		}

		@OnlyIn(Dist.CLIENT)
		public void clientLoad(FMLClientSetupEvent event) {
		}

		@Override
		public int compareTo(ModElement other) {
			return this.sortid - other.sortid;
		}
	}
}
